services:
    - docker

before_install :
    - docker build -t vishnuvardandonti/reacttest -f ./client/Dockerfile.dev ./client

scripts : 
    - docker run -e CI=true vishnuvardandonti/reacttest npm test -- --coverage

after_success :
    - echo "$docker_user"
    - echo "$docker_secret" | docker login -u "$docker_user" --password-stdin
    - docker build -t vishnuvardandonti/multidocker-client ./client
    - docker build -t vishnuvardandonti/multidocker-nginx ./nginx
    - docker build -t vishnuvardandonti/multidocker-server ./server
    - docker build -t vishnuvardandonti/multidocker-worker ./worker
    # Login to the docker CLI
    
    #pushing docker files
    - docker push vishnuvardandonti/multidocker-client
    - docker push vishnuvardandonti/multidocker-nginx
    - docker push vishnuvardandonti/multidocker-server
    - docker push vishnuvardandonti/multidocker-worker

deploy :
    provider : elasticbeanstalk
    region : us-east-2
    app : multi-docker
    env : MultiDocker-env
    bucket_name : elasticbeanstalk-us-east-2-416789637987
    bucket_path : multidocker
    on :
        branch : master
    access_key_id : $AWS_ACCESS_KEY
    secret_access_key : $AWS_SECRET_KEY

