services:
  -docker

before_install :
    - docker build -t vishnuvardandonti/reacttest -f ./client/Dockerfile.dev ./client

scripts : 
    - docker run -e CI=true vishnuvardandonti/reacttest npm test -- --coverage

after_success :
    - echo "$docker-secret" | docker login -u "$docker-user" --password-stdin
    - docker build -t vishnuvardandonti/multidocker-client ./client
    - docker build -t vishnuvardandonti/multidocker-nginx ./nginx
    - docker build -t vishnuvardandonti/multidocker-server ./server
    - docker build -t vishnuvardandonti/multidocker-worker ./worker
    # Login to the docker CLI
    
    #pushing docker files
    - docker push vishnuvardandonti/multidocker-client
    - docker push vishnuvardandonti/multidocker-nginx
    - docker push vishnuvardandonti/multidocker-server
    - docker push vishnuvardandonti/multidocker-worker

